import { Category } from "@/types/categories";

  export const category_API_test: Category[] = [
    {
      id: "1",
      label: "Artículos de librería",
      parentId: null,
      count: 3,
      isChecked: false,
      commission: null,
      subcategory: [
        {
          id: "11",
          label: "Apples",
          parentId: "1",
          count: 2,
          commission: null,
          isChecked: false,
          subcategory: [
            {
              id: "111",
              label: "Red",
              parentId: "11",
              commission: null,
              count: null,
              isChecked: false,
              subcategory: [],
            },
            {
              id: "112",
              label: "Green",
              parentId: "11",
              count: null,
              commission: null,
              isChecked: false,
              subcategory: [],
            },
          ],
        },
        {
          id: "12",
          label: "Bananas",
          parentId: "1",
          count: 1,
          commission: null,
          isChecked: false,
          subcategory: [
            {
              id: "121",
              label: "Yellow",
              parentId: "12",
              count: null,
              commission: null,
              isChecked: false,
              subcategory: [],
            },
          ],
        },
        {
          id: "13",
          label: "Oranges",
          parentId: "1",
          count: null,
          commission: null,
          isChecked: false,
          subcategory: [],
        },
      ],
    },
    {
      id: "2",
      label: "Celulares",
      parentId: null,
      commission: null,
      count: 3,
      isChecked: false,
      subcategory: [
        {
          id: "21",
          label: "Carrots",
          parentId: "2",
          count: null,
          commission: null,
          isChecked: false,
          subcategory: [],
        },
        {
          id: "22",
          label: "Broccoli",
          parentId: "2",
          count: null,
          commission: null,
          isChecked: false,
          subcategory: [],
        },
        {
          id: "23",
          label: "Spinach",
          parentId: "2",
          count: null,
          commission: null,
          isChecked: false,
          subcategory: [],
        },
      ],
    },
    {
      id: "3",
      label: "Climatización",
      parentId: null,
      count: 3,
      commission: null,
      isChecked: false,
      subcategory: [
        {
          id: "31",
          label: "Cats",
          parentId: "3",
          count: null,
          commission: null,
          isChecked: false,
          subcategory: [],
        },
        {
          id: "32",
          label: "Dogs",
          parentId: "3",
          count: 1,
          commission: null,
          isChecked: false,
          subcategory: [
            {
              id: "321",
              label: "Puppies",
              parentId: "32",
              count: 1,
              commission: null,
              isChecked: false,
              subcategory: [
                {
                  id: "3211",
                  label: "Golden Retrievers",
                  parentId: "321",
                  count: null,
                  commission: null,
                  isChecked: false,
                  subcategory: [],
                },
              ],
            },
          ],
        },
        {
          id: "33",
          label: "Birds",
          parentId: "3",
          count: null,
          commission: null,
          isChecked: false,
          subcategory: [],
        },
      ],
    },
  ];
  